################################################################################
#
# HEMS - Home Energy Management System
#
# Version : 0.1.0-alpha
#
# Datei : hems.yaml
#
################################################################################

################################################################################
# Helpers
################################################################################

input_boolean: !include hems/helpers/booleans.yaml

input_number: !include hems/helpers/numbers.yaml

input_datetime: !include hems/helpers/datetime.yaml

input_select: !include hems/helpers/select.yaml

################################################################################
# Templates
################################################################################

template: !include hems/templates/templates.yaml

################################################################################
# Scripts
################################################################################

script: !include hems/scripts/scripts.yaml

################################################################################
# Automations
################################################################################

automation: !include hems/automations/automations.yaml
