################################################################################
#
# HEMS - Home Energy Management System
#
# Version : 0.1.0-alpha
#
# Datei : hems.yaml
#
################################################################################

################################################################################
# Helpers
################################################################################

input_boolean: !include helpers/booleans.yaml

input_number: !include helpers/numbers.yaml

input_datetime: !include helpers/datetime.yaml

input_select: !include helpers/select.yaml

################################################################################
# Templates
################################################################################

template: !include templates/templates.yaml

################################################################################
# Scripts
################################################################################

script: !include scripts/scripts.yaml

################################################################################
# Automations
################################################################################

automation: !include automations/automations.yaml
