################################################################################
#
# HEMS - Home Energy Management System
#
# Version : 0.1.0-alpha
#
################################################################################

input_boolean: !include helpers/booleans.yaml

input_number: !include helpers/numbers.yaml

input_datetime: !include helpers/datetime.yaml

input_select: !include helpers/select.yaml

template: !include templates/templates.yaml

script: !include scripts/scripts.yaml

automation: !include automations/automations.yaml
