################################################################################
#
# HEMS - Home Energy Management System
#
# Version : 0.1.0-alpha
#
# Datei : entities.yaml
#
################################################################################

wallbox:

  ampere: number.goe_082888_amp

  force_state: select.goe_082888_frc

  phase_mode: select.goe_082888_psm

  phase_switching: binary_sensor.goe_082888_fsp

  connected: binary_sensor.goe_082888_car_0

  charging_power: sensor.goe_082888_nrg_11

energy:

  grid_power: sensor.pv_charge_grid_power

battery:

  power:

pv:

  production:

vehicle:

  tesla_connected:

  tesla_charging:
