hems_log:
  alias: HEMS - Log Message
  description: Einheitliches Logging für alle HEMS-Komponenten

  fields:
    manager:
      description: Managername (POWER, START, STOP ...)
      example: POWER

    level:
      description: debug, info, warning, error
      example: debug

    message:
      description: Lognachricht
      example: Avail=4500W Target=7A

  sequence:

    - variables:
        log_level: "{{ level | default('debug') | lower }}"
        log_message: >
          [HEMS][{{ manager | upper }}]
          {{ message }}

    - choose:

        - conditions:
            - condition: template
              value_template: "{{ log_level == 'debug' }}"
          sequence:
            - action: system_log.write
              data:
                level: debug
                message: "{{ log_message }}"

        - conditions:
            - condition: template
              value_template: "{{ log_level == 'info' }}"
          sequence:
            - action: system_log.write
              data:
                level: info
                message: "{{ log_message }}"

        - conditions:
            - condition: template
              value_template: "{{ log_level == 'warning' }}"
          sequence:
            - action: system_log.write
              data:
                level: warning
                message: "{{ log_message }}"

      default:
        - action: system_log.write
          data:
            level: error
            message: "{{ log_message }}"
