hems_log:
  alias: HEMS - Log Message
  description: Einheitliches Logging für alle HEMS-Komponenten
  mode: queued
  max: 100

  fields:
    manager:
      description: Managername (POWER, START, STOP, ...)
      example: POWER

    level:
      description: debug, info, warning oder error
      example: debug

    message:
      description: Lognachricht
      example: Avail=4500W Target=7A

  sequence:

    - variables:
        log_manager: "{{ manager | default('GENERAL') }}"
        log_level: "{{ level | default('debug') | lower }}"
        log_text: "{{ message | default('') }}"

    - action: system_log.write
      data:
        level: "{{ log_level }}"
        logger: hems
        message: >-
          [HEMS][{{ log_manager | upper }}] {{ log_text }}
