###############################################################################
#
# HEMS - Home Energy Management System
#
# Version : 0.1.1-alpha
#
# Datei : automations.yaml
#
################################################################################

- id: hems_controller

  alias: HEMS - Controller

  description: >
    Startet zyklisch den HEMS Controller.

  mode: single

  trigger:

    - trigger: time_pattern
      seconds: "/30"

  action:

    - action: script.hems_controller
